const REGISTER_URL = "https://mojie.app/register?aff=U4tPktul";
const CODEX_SERVICE_URL = "https://tonecho.xyz/register?aff=9PPNTWSTRL7B";
const baseSteps = [
  { id:"vpn", title:"配置 VPN", short:"VPN", summary:"准备稳定的网络环境", note:"先完成网络配置，再进行下载和注册。", body:()=>`<p>使用魔戒 App 完成注册并进入服务页面。点击下方链接（链接可以点击跳转，也可以复制）</p>${linkBlock(REGISTER_URL,"魔戒注册链接")}<div class="media-stack">${media("image1.png","下载客户端","找到 Windows 客户端并下载。")}${media("image2.png","选择一个订阅套餐","按自己的使用强度选择套餐。")}${media("image8.png","VPN的启用","点击使用文档—&gt;Windows教程，根据教程配置")}</div>` },
  { id:"network", title:"连接网络", short:"网络", summary:"打开全局网络配置", note:"电话号码国家应与 VPN 所在国家一致。（电话号码后面会用到）", body:()=>`<div class="media-stack">${media("image3.png","通过客户端改变 IP","优先选择美国或加拿大线路。")}${media("image4.png","使用 VPN 的配置","打开系统代理、虚拟网卡，出站模式设为全局。")}</div><ol><li>确认网络速度有正常波动。</li><li>检查加速器中间的网络检测是否显示新的 IP。</li></ol>` },
  { id:"download", title:"下载 Codex", short:"下载", summary:"选择一个下载路径", note:"两种下载方式对应不同的版本维护方式。", branch:"download", body:()=>`<p>ChatGPT 与 Codex 已合并在同一个系统中，请选择下载方式：</p>${branchOptions("download",[["legacy","仓库安装包","稳定性优先，适合需要旧版 ChatGPT 的用户。"],["store","Microsoft Store","最新版并自动更新，适合希望保持最新功能的用户。"]])}` },
  { id:"account", title:"注册账号", short:"账号", summary:"使用电话号码完成注册", note:"电话号码必须与 VPN 所在国家一致，VPN 保持全局模式。", body:()=>`<p>因为无论使用哪种下载方式，使用 Codex 最终都需要绑定电话号码。</p>${linkBlock(CODEX_SERVICE_URL,"通客注册服务")}<div class="text-step-box"><h3>打开通客服务</h3><p>进入服务页面并登录。</p></div><div class="media-stack">${media("image5.png","获取短信接收号码","点击“通客自助接码”，按页面提示操作。")}</div><div class="callout">注册时选择的电话号码国家要与 VPN 所在国家一致。</div>` },
  { id:"subscription", title:"选择订阅方式", short:"订阅", summary:"选择 API 或官方套餐", note:"选择适合自己的订阅方式。", branch:"subscription", body:()=>`<p>根据使用频率和预算选择一条订阅路径：</p>${branchOptions("subscription",[["api","API 方案","先配置 CC switch，再获取 API 并选择模型分组。"],["official","官方套餐","购买官方 Plus 或 Pro 套餐，并按页面提示开通。"]])}<div id="subscription-guidance">${subscriptionGuidance(selections.subscription)}</div>` }
];
const branchSteps = {
  legacy:[{id:"legacy-install",title:"安装仓库版本",short:"安装包",summary:"下载并安装仓库中的旧版程序",note:"旧版相对稳定，但只能使用 GPT-5.6。",body:()=>`<div class="branch-page"><h3>请下载仓库中的安装包</h3><p>在你的 GitHub 仓库中找到安装文件，下载后按 Windows 安装向导完成安装。</p><div class="callout">安装完成后返回此页面，点击下一步。</div></div>`}],
  store:[{id:"store-install",title:"安装 Store 版本",short:"Store",summary:"从 Microsoft Store 安装最新版",note:"Store 版本会自动更新。",body:()=>`<div class="branch-page"><h3>打开 Microsoft Store</h3><p>搜索“GPT”或“Codex”，选择官方应用并完成安装，随后回到此页面。</p></div>`}],
};
function subscriptionGuidance(selection){
  if(selection==="api") return `<div class="branch-guidance"><h3>API 方案指导</h3><div class="text-step-box"><h3>配置 CC switch</h3><p>下载 CC switch，通过网页按照指引完成环境配置。</p></div><p>获取 API：API 相当于带有个人信息认证的账户，调用模型会从对应账户直接扣费，不用订阅官方套餐。</p><div class="media-stack">${media("image7.png","选择模型分组","倍率越高，单个 token 的成本越高，作者建议 Pro 组通常已经够用。")}</div><div class="warning-block">使用 API 前核对价格、倍率、额度和扣费主体，不要公开 API key。</div><div class="warning-block">使用API可能会导致使用的模型降智，请谨慎考虑购买方案。</div></div>`;
  if(selection==="official") return `<div class="branch-guidance"><h3>官方套餐指导</h3><p>购买官方 Plus 或 Pro 套餐，进入页面中的开通入口，按页面提示完成购买和开通。</p><div class="media-stack">${media("image2.png","进入购买订阅","在服务页面的“购买订阅”入口选择套餐。")}</div><div class="warning-block">套餐名称、金额、账单周期、退款规则和优惠以实际结算页为准。</div></div>`;
  return "";
}
function media(src,title,text){return `<figure class="media-item"><img src="assets/${src}" alt="${title}" loading="lazy"><figcaption><strong>${title}</strong><span>${text}</span></figcaption></figure>`}
function linkBlock(url,label){return `<div class="link-block"><a href="${url}" target="_blank" rel="noopener noreferrer" class="external-link">${label}<small>${url}</small></a><button class="copy-link" type="button" data-copy="${encodeURIComponent(url)}" title="复制链接" aria-label="复制链接">⧉</button></div>`}
function branchOptions(group,opts){return `<div class="branch-grid" data-branch-group="${group}">${opts.map(([id,title,desc])=>`<button class="branch-option" type="button" data-branch="${id}" aria-pressed="false"><strong>${title}</strong><span>${desc}</span></button>`).join("")}</div>`}
let current=Number.parseInt(localStorage.getItem("codex-guide-step")||"-1",10);let selections={};try{selections=JSON.parse(localStorage.getItem("codex-guide-branches")||"{}")}catch{selections={}}if(!Number.isInteger(current))current=-1;
const app=document.querySelector("#app"),toast=document.querySelector("#toast");
function flow(){return [...baseSteps.slice(0,3),...(selections.download?branchSteps[selections.download]:[]),...baseSteps.slice(3)]}
function render(){if(current<0)return welcome();const steps=flow();if(current>=steps.length)current=steps.length-1;const step=steps[current],percent=Math.round((current+1)/steps.length*100);app.innerHTML=`<section class="step-layout"><div class="progress-head"><span>第 <b>${current+1}</b> / ${steps.length} 步</span><b>${percent}%</b></div><div class="progress-track"><div class="progress-value" style="width:${percent}%"></div></div><nav class="step-nav" aria-label="步骤导航">${steps.map((item,i)=>`<button class="step-dot ${i===current?"active":""} ${i<current?"done":""}" type="button" data-jump="${i}"><i>${i<current?"✓":i+1}</i>${item.short}</button>`).join("")}</nav><article class="step-card"><aside class="step-aside"><span class="step-index">STEP ${String(current+1).padStart(2,"0")}</span><h1>${step.title}</h1><p>${step.summary}</p><p class="aside-note">${step.note}</p></aside><div class="step-content">${step.body()}</div></article><div class="nav-dock"><button class="nav-button" type="button" data-action="prev" ${current===0?"disabled":""}>← 上一步</button><button class="nav-button primary" type="button" data-action="next">${current===steps.length-1?"完成指南":"下一步 →"}</button></div></section>`;syncBranches();window.scrollTo({top:0,behavior:"smooth"})}
function welcome(){app.innerHTML=`<section class="welcome"><div><span class="eyebrow">STEP BY STEP · WINDOWS</span><h1>Codex<br><span>安装指南</span></h1><p class="lead">从网络配置、软件下载到账号注册和订阅选择，按当前路径完成每一步。</p><div class="welcome-meta"><span>图文说明</span><span>分支路径</span><span>移动端适配</span></div></div><div class="welcome-visual"><div class="visual-panel"><div class="visual-core">C</div><span class="visual-label">Windows setup flow</span></div></div><div class="nav-dock"><button class="nav-button primary" type="button" data-action="start">开始指南 →</button></div></section>`}
function syncBranches(){document.querySelectorAll("[data-branch-group]").forEach(group=>{const selected=selections[group.dataset.branchGroup];group.querySelectorAll("[data-branch]").forEach(btn=>{const on=btn.dataset.branch===selected;btn.classList.toggle("selected",on);btn.setAttribute("aria-pressed",String(on))});if(group.dataset.branchGroup==="subscription"){const guidance=document.querySelector("#subscription-guidance");if(guidance)guidance.innerHTML=subscriptionGuidance(selected)}})}
function save(){localStorage.setItem("codex-guide-branches",JSON.stringify(selections));localStorage.setItem("codex-guide-step",String(current))}
function showToast(msg){toast.textContent=msg;toast.classList.add("visible");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("visible"),2200)}
async function copyLink(value){try{await navigator.clipboard.writeText(decodeURIComponent(value));showToast("链接已复制")}catch{showToast("复制失败，请手动复制")}}
document.addEventListener("click",event=>{const target=event.target.closest("button");if(!target)return;const action=target.dataset.action;if(action==="toggle-theme"){document.body.classList.toggle("dark");localStorage.setItem("codex-guide-theme",document.body.classList.contains("dark")?"dark":"light");return}if(action==="start"){current=0;save();render()}else if(action==="prev"){current=Math.max(0,current-1);save();render()}else if(action==="next"){const step=flow()[current];if(step.branch&&!selections[step.branch])return showToast("请先选择一条路径");if(current>=flow().length-1){showToast("指南已完成");current=-1;localStorage.removeItem("codex-guide-step");render()}else{current++;save();render()}}else if(target.dataset.jump){current=Number(target.dataset.jump);save();render()}else if(target.dataset.copy)copyLink(target.dataset.copy);const branch=target.closest("[data-branch]");if(branch){selections[branch.closest("[data-branch-group]").dataset.branchGroup]=branch.dataset.branch;save();syncBranches()}});if(localStorage.getItem("codex-guide-theme")==="dark")document.body.classList.add("dark");render();
